spring:
  application:
    name: eureka-server
server:
  port: 8761
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
