spring.application.name=GatewayMS
server.port=9000

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.default-produces-media-type=application/json
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.urls[0].name=GatewayMS
springdoc.swagger-ui.urls[0].url=/v3/api-docs
springdoc.swagger-ui.urls[1].name=UserMS
springdoc.swagger-ui.urls[1].url=/user-docs/v3/api-docs
springdoc.swagger-ui.urls[2].name=ProfileMS
springdoc.swagger-ui.urls[2].url=/profile-docs/v3/api-docs
springdoc.swagger-ui.urls[3].name=AppointmentMS
springdoc.swagger-ui.urls[3].url=/appointment-docs/v3/api-docs
springdoc.swagger-ui.urls[4].name=PharmacyMS
springdoc.swagger-ui.urls[4].url=/pharmacy-docs/v3/api-docs
springdoc.swagger-ui.urls[5].name=MediaMS
springdoc.swagger-ui.urls[5].url=/media-docs/v3/api-docs
springdoc.swagger-ui.urls[6].name=EurekaServer
springdoc.swagger-ui.urls[6].url=/eureka-docs/v3/api-docs

# Dedupe to remove duplicate headers
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin RETAIN_UNIQUE
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# CORS Configuration - Correctly broken down
spring.cloud.gateway.globalcors.cors-configurations[/**].allowed-origins[0]=http://localhost:3000
spring.cloud.gateway.globalcors.cors-configurations[/**].allowed-headers[0]=*
spring.cloud.gateway.globalcors.cors-configurations[/**].allowed-methods[0]=GET
spring.cloud.gateway.globalcors.cors-configurations[/**].allowed-methods[1]=POST
spring.cloud.gateway.globalcors.cors-configurations[/**].allowed-methods[2]=PUT
spring.cloud.gateway.globalcors.cors-configurations[/**].allowed-methods[3]=DELETE
spring.cloud.gateway.globalcors.cors-configurations[/**].allowed-methods[4]=OPTIONS

# Routes
spring.cloud.gateway.routes[0].id=UserMS
spring.cloud.gateway.routes[0].uri=lb://UserMS
spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**
spring.cloud.gateway.routes[0].filters[0]=TokenFilter

# Routes
spring.cloud.gateway.routes[1].id=profileMS
spring.cloud.gateway.routes[1].uri=lb://ProfileMS
spring.cloud.gateway.routes[1].predicates[0]=Path=/profile/**
spring.cloud.gateway.routes[1].filters[0]=TokenFilter

# Routes
spring.cloud.gateway.routes[2].id=AppointmentMS
spring.cloud.gateway.routes[2].uri=lb://AppointmentMS
spring.cloud.gateway.routes[2].predicates[0]=Path=/appointment/**
spring.cloud.gateway.routes[2].filters[0]=TokenFilter


# Routes
spring.cloud.gateway.routes[3].id=PharmacyMS
spring.cloud.gateway.routes[3].uri=lb://PharmacyMS
spring.cloud.gateway.routes[3].predicates[0]=Path=/pharmacy/**
spring.cloud.gateway.routes[3].filters[0]=TokenFilter


spring.cloud.gateway.routes[4].id=MediaMS
spring.cloud.gateway.routes[4].uri=lb://MediaMS
spring.cloud.gateway.routes[4].predicates[0]=Path=/media/**
spring.cloud.gateway.routes[4].filters[0]=TokenFilter

spring.cloud.gateway.routes[5].id=EurekaDocs
spring.cloud.gateway.routes[5].uri=http://localhost:8761
spring.cloud.gateway.routes[5].predicates[0]=Path=/eureka-docs/**
spring.cloud.gateway.routes[5].filters[0]=RewritePath=/eureka-docs/(?<segment>.*), /${segment}

spring.cloud.gateway.routes[6].id=UserMSDocs
spring.cloud.gateway.routes[6].uri=lb://UserMS
spring.cloud.gateway.routes[6].predicates[0]=Path=/user-docs/**
spring.cloud.gateway.routes[6].filters[0]=RewritePath=/user-docs/(?<segment>.*), /${segment}
spring.cloud.gateway.routes[6].filters[1]=TokenFilter

spring.cloud.gateway.routes[7].id=ProfileMSDocs
spring.cloud.gateway.routes[7].uri=lb://ProfileMS
spring.cloud.gateway.routes[7].predicates[0]=Path=/profile-docs/**
spring.cloud.gateway.routes[7].filters[0]=RewritePath=/profile-docs/(?<segment>.*), /${segment}
spring.cloud.gateway.routes[7].filters[1]=TokenFilter

spring.cloud.gateway.routes[8].id=AppointmentMSDocs
spring.cloud.gateway.routes[8].uri=lb://AppointmentMS
spring.cloud.gateway.routes[8].predicates[0]=Path=/appointment-docs/**
spring.cloud.gateway.routes[8].filters[0]=RewritePath=/appointment-docs/(?<segment>.*), /${segment}
spring.cloud.gateway.routes[8].filters[1]=TokenFilter

spring.cloud.gateway.routes[9].id=PharmacyMSDocs
spring.cloud.gateway.routes[9].uri=lb://PharmacyMS
spring.cloud.gateway.routes[9].predicates[0]=Path=/pharmacy-docs/**
spring.cloud.gateway.routes[9].filters[0]=RewritePath=/pharmacy-docs/(?<segment>.*), /${segment}
spring.cloud.gateway.routes[9].filters[1]=TokenFilter

spring.cloud.gateway.routes[10].id=MediaMSDocs
spring.cloud.gateway.routes[10].uri=lb://MediaMS
spring.cloud.gateway.routes[10].predicates[0]=Path=/media-docs/**
spring.cloud.gateway.routes[10].filters[0]=RewritePath=/media-docs/(?<segment>.*), /${segment}
spring.cloud.gateway.routes[10].filters[1]=TokenFilter

